name: build

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  packages: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
        if: github.event_name != 'pull_request'
      - uses: docker/setup-buildx-action@v3
        if: github.event_name != 'pull_request'
      - uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean --snapshot ${{ github.event_name == 'pull_request' && '--skip=docker' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
      - uses: actions/upload-artifact@v4
        with:
          name: bandgo_ci_build
          path: |
            dist/*.tar.gz
            dist/*.zip
            dist/*.txt
